### ISSUE TITLE
Path to Email ID's

### ISSUE THREAD

**Issue by ghost** [xomarquez27/tweet-schwab-trades#1]
Hey xomarquez27, 

I am trying to learn a bit about API's and python and figured this would be a fun 'dive in' to get my feet wet. I think I have everything configured and ready to go but I noticed the "Replace with path/to/your/folder/email_ids.txt" section where I need to edit: file_location = '/home/xavier/Desktop/Python/Schwab_Tweets/email_ids.txt'

What exactly needs to be contained in the email_ids.txt? 

Thanks!

**Comment by ghost** [comment]
Non issue, never mind.

**Comment by xomarquez27** [comment]
emails_ids.txt will get populated by the email ids of the relevant emails including schwab trading notifications. I am not sure if this code still works as Google changed API access to Gmail a few months ago. I moved to other trading platforms since Schwab is so slow, so I haven't tested this code.

**Comment by ghost** [comment]
Thanks for the quick follow up, which platform did you move to? I may see if Schwab has an API for their Street Smart Edge application. Might be a little quicker.

**Comment by xomarquez27** [comment]
TD Ameritrade. However TD Ameritrade does not send out info about trade confirmations in their emails like Schwab does.
